### PR TITLE
Fix js icu with hashtable

### PR DESCRIPTION
**Pull request by fabriceleal**
Migrated isLower, isUpper, isDigit, isAlpha and isPrint to use hashtables instead of infinite ifs, the file is now 3.6M 😅 By the way, if you want, I can also migrate toUpper and toLower, although these include just a few corner cases and rely mostly on javascript's native toUpperCase() and toLowerCase()

### CODE REVIEW

**Comment by fabriceleal** [comment]
That isPrint hashtable is quite big; if you're still interested in the coded binary search approach, I improved the generator to stop at a maximum depth of ifs (in this case, 7) and then rely on the sequentiality of these chars' properties  
(this is in another branch of mine) https://github.com/fabriceleal/urweb/commit/2f4defd8d1a782217f0372d50a43f71686d3baf3#diff-867e8dfbbc36419eefc0dfdf9db32883R3549

**Comment by ashalkhakov** [comment]
What if you used bitset for the lookup? Then you could encode the whole dictionary into a very long string (say expressed in hexadecimal or in decimal).

**Comment by achlipala** [comment]
I like this bitset idea!  @fabriceleal, is it feasible to implement and experiment with?

**Comment by fabriceleal** [comment]
It seems to work nicely! and the file is down to 210kb. I've encoded the dictionary into a native javascript array, I'll try to make this work with typed arrays or with the base64 approach to  improve performance / save space https://github.com/fabriceleal/urweb/blob/fix-js-icu-with-bitlookups/lib/js/urweb.js#L231

**Comment by fabriceleal** [comment]
Ok I tried the base64 approach but it gets horribly slow (I was unpacking it on load), so I just discarded it; I got the typed arrays to work, but it makes the file a bit bigger (251kb) and there's no performance gain, although the code does appear lighter around the "shorter" bitmaps for isLower, isUpper and isDigit. So as it stands, I have available the native array approach (https://github.com/fabriceleal/urweb/blob/fix-js-icu-with-bitlookups/lib/js/urweb.js#L32) and the typed array approach (https://github.com/fabriceleal/urweb/blob/fix-js-icu-with-typedarray/lib/js/urweb.js#L32)

**Comment by achlipala** [comment]
When did major browsers uniformly adopt typed arrays?  I wonder if old-version compatibility seals the argument for the simple "native" arrays.

**Comment by fabriceleal** [comment]
Not sure how reliable, but I found this https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#Browser_compatibility 

I'm personally also more inclined towards native arrays

**Comment by achlipala** [comment]
I don't know enough about browser version histories to interpret the table you linked to, but, if native arrays also have other points in their favor and none against, then perhaps it is time to finalize that approach in a PR!  Is the current content of this PR already what you favor as the final version to merge?

**Comment by fabriceleal** [comment]
I'll create another PR, with the branch that has the proper name and cleaner commit history

**Pull request closed without merging**
