### PR TITLE
Some basic math functions: pow, sqrt, sin, cos, log, exp 

### PR DESCRIPTION
**Pull request by karsar**
I've found that some basic math functions are lacking. For mathematical computations it's always better to use a specialized library, but if you need to add just square root, say for calculating standard deviation to present data nicely, adding a whole library and potentially using FFI seems to be an overkill. 
Basic functions, I've felt I miss, are pow, sqrt (basic statistics), sin, cos, log (to change the scale if required), exp.

### CODE REVIEW

**Comment by vizziv** [comment]
If we're doing this, it seems like there's no harm in also adding other basic functions from `math.h`. (`atan2` in particular comes up pretty often for me.)

**Comment by karsar** [comment]
It would be pretty cool to know what else except atan2 is useful for people to add. There are functions like  hyperbolic cosine that I don't often see in practice. Maybe just acos, asin, atan, atan2?

**Comment by AlexanderAA** [comment]
abs and sinh, cosh, tanh? 

It would be nice to have all functions which are available both in Javascripts' Math.* and C math.h

**Comment by karsar** [comment]
If I'm not mistaken, there are no sinh, cosh, tanh in JS Math.* so only abs and floor remain.
I've considered that calculating abs in urweb code is trivial, while getting square root or cosine is not so.
However, to be consistent I'll add abs and floor.

**Comment by AlexanderAA** [comment]
I've checked quickly at the link below - sinh, cosh, tanh seem to be included into ECMAScript 2015 (6th Edition, ECMA-262). 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math

**Comment by karsar** [comment]
That's something I didn't know. This update is quite new and according to Wikipedia (outdated info?) not all browsers completely support this new standard at the moment. Hence, I'm not sure if it's better to stick to the old one until someone in need of those functions appears. Maybe provide them as part of external specialized library. Of course, I will add those functions if majority wants, but I need to be sure that its something needed.

**Comment by AlexanderAA** [comment]
Yes, maybe it is better to ignore them for now, these functions are not very important anyway

**Comment by achlipala** [comment]
Thanks for the (joint) initiative, everyone!  I'll wait another day or so to see if the discussion stabilizes, then I'll merge the latest code.

**Pull request merged**
