### PR TITLE
Adding: cradio (support for client-side radio box).

### PR DESCRIPTION
**Pull request by ashalkhakov**
This one seems to be entirely missing.

I don't know how to get it initialized properly on the client, so I just used `setTimeout` for that.

The idea is that all radio buttons that belong to a single a group will have the same source.

### CODE REVIEW

**Comment by ashalkhakov** [comment]
I just took at a look at the spec, seems like this design would not support multiple groups on the same page. Oops.

**Comment by achlipala** [comment]
Right; it looks like the encoding you've implemented isn't flexible enough to cover common uses of radio buttons.  Would you like to go back to the drawing board?  I'll be happy to accept a patch that allows multiple radio groups on a page.

**Comment by ashalkhakov** [comment]
Sure, no problem.

**Comment by ashalkhakov** [comment]
Actually, it works fine for me on Chrome. Curious!

**Pull request merged**
