### PR TITLE
Webrtc chat demo using webrtc module in Ur/Web

### PR DESCRIPTION
**Pull request by hkasera**
Hello,

This is a PR as a followup to [this](http://www.impredicative.com/pipermail/ur/2017-November/002705.html) mailing discussion. 

Please have a look  and feel free to let us know if it requires any changes. We hope to hear your valuable feedback on this.

Thank you!

### CODE REVIEW

**Comment by achlipala** [comment]
Thanks for all this effort.  I really want to get to inspecting what you've come up with, but I'm swamped with work for now.

**Comment by ashalkhakov** [comment]
What if we moved this to a library? It looks promising to me!

**Comment by achlipala** [comment]
I've been making progress wading through the backlog of Ur/Web issues, and I hope to get to this one soon!  Then I will weigh in on the right way to incorporate it.

**Comment by achlipala** [comment]
Meh, please ignore that review comment.  I am still figuring out how to use reviewing on GitHub.  But know that I am finally reading now!

**Comment by achlipala** [comment]
OK, after my long delay being distracted by life in general, here are my thoughts on this PR.

It's great to have a demonstration that Ur/Web can be connected to WebRTC with only a moderate amount of code!  It can only help the Ur/Web community to have this code online somewhere.

At the moment, the code looks more like a one-off application than like a library.  I don't see a clearly defined API for easy use in other applications.  Yet I presume a lot of the code is quite general and *could* be library-ized.  So it doesn't seem to make sense for merging into the main Ur/Web distribution.

There are also some style issues that would leave me wary of blessing this code.
- There are few comments in the code, which admittedly tends to be the case of so much code that we write these days!
- There is a lot of use of the `string` type, which goes against the Ur/Web philosophy of using expressive types to make clear what kind of data are flowing where.
- Some JavaScript code seems to be mucking with HTML directly, rather than going through the Ur/Web functional-reactive interface, and it isn't clear why.  I wouldn't want to suggest that it's idiomatic to use JavaScript to mutate page contents, within an Ur/Web application.
- And, yes, there is a Mac-specific `.DS_store` file checked in, but that would be easy to fix.

So my guess is that this PR will be closed soon without merging, but a variety of useful things could be done with this code, depending on how much work you are willing to put into cleaning up and/or library-izing it.

**Pull request closed without merging**
